### ISSUE TITLE
Global rate limiting (Limit CloudFlare banning)

### ISSUE THREAD

**Issue by lexicalunit** [Rapptz/discord.py#8169]
### Summary

Global rate limiting on any and all network requests across the library

### What is the feature request for?

The core library

### The Problem

My bot has got popular enough that, since switching to slash commands, it now occasionally hits that 50 requests per second limit which triggers a CloudFlare ban. See https://discord.com/developers/docs/topics/rate-limits#global-rate-limit for more details:
> **Global Rate Limit**
> All bots can make up to 50 requests per second to our API. This is independent of any individual rate limit on a route. If your bot gets big enough, based on its functionality, it may be impossible to stay below 50 requests per second during normal operations.
> 
> Global rate limit issues generally show up as repeatedly getting banned from the Discord API when your bot starts (see below). If your bot gets temporarily CloudFlare banned from the Discord API every once in a while, it is most likely not a global rate limit issue. You probably had a spike of errors that was not properly handled and hit our error threshold.
> 
> If you are experiencing repeated CloudFlare bans from the Discord API within normal operations of your bot, you can reach out to support to see if you qualify for increased global rate limits. You can contact Discord support using https://dis.gd/contact.
> 
> [Interaction endpoints](https://discord.com/developers/docs/interactions/receiving-and-responding#endpoints) are not bound to the bot's Global Rate Limit.

I've contacted Discord Support multiple times over the course of the last 4 months to try and get my bot's limit raised from 50 to something higher, but they either just ignore my requests (one support ticket has had no response in 3 months). Or their automatic bot just closes my support tickets saying "Discord Support is for bot developers only, you might be in the wrong place."

🤦🏻‍♀️

### The Ideal Solution

Before any network request is made by any part of the library, check that within the last 1 second we have not made too many requests. Like say if 49 requests have been made, then sleep some amount of time before making the next request.

### The Current Solution

As far as I can tell there is no solution to this issue as Discord Support is entirely unhelpful if not outright antagonistic to developers of bots.

**Comment by NCPlayz** [comment]
Hi! This might be a reach, but do you happen to be using `cchardet` (one of the suggested speed-up dependencies for discord.py / aiohttp) on Python 3.10?

From what I experienced, it seems that it's very unstable on Python 3.10 and results in multiple re-request attempts, and hitting the global rate limit.

**Comment by lexicalunit** [comment]
I'm not sure if I'm using `cchardet`. I don't see it listed when I run `pip freeze`, tho there is a `chardet` (one `c`):
```shell
➜ pip freeze | grep chardet
chardet @ file:///Users/me/Library/Caches/pypoetry/artifacts/1b/0a/2f/b74d5b8fa13926161c701f0aef60e2577b6214bc9eef13b96784d696a0/chardet-4.0.0-py2.py3-none-any.whl
```

And it's mentioned in my lock file too:
```plain
➜ cat poetry.lock| grep -C 3 cchardet
yarl = ">=1.0,<2.0"

[package.extras]
speedups = ["aiodns", "brotlipy", "cchardet"]

[[package]]
name = "aiohttp-jinja2"
--

[package.extras]
docs = ["sphinx (==4.4.0)", "sphinxcontrib-trio (==1.1.2)", "sphinxcontrib-websupport", "typing-extensions"]
speed = ["orjson (>=3.5.4)", "aiodns (>=1.1)", "brotli", "cchardet"]
test = ["coverage", "pytest", "pytest-asyncio", "pytest-cov", "pytest-mock"]
voice = ["PyNaCl (>=1.3.0,<1.6)"]
```

Here's my packages in `pyproject.toml` for reference:
```toml
[tool.poetry.dependencies]
Babel = "^2.9.1"
PyYAML = "^6.0"
SQLAlchemy = "^1.4.36"
SQLAlchemy-Utils = "^0.38.2"
aiohttp = "<3.8.0"
aiohttp-jinja2 = "^1.5"
aiohttp-retry = "^2.4.6"
alembic = "^1.8.0"
asgiref = "^3.5.2"
click = "^8.0.4"
coloredlogs = "^15.0.1"
datadog = "^0.44.0"
ddtrace = ">=0.59,<1.1"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git", rev = "master"}
dunamai = "^1.12.0"
expiringdict = "^1.2.1"
gunicorn = "^20.1.0"
humanize = "^4.2.0"
hupper = "^1.10.3"
importlib-resources = "^5.8.0"
psycopg2-binary = "^2.9.3"
python = '>=3.10,<4'
python-dateutil = "^2.8.2"
python-dotenv = "^0.20.0"
pytz = "^2022.1"
supervisor = "^4.2.4"
types-PyYAML = "^6.0.8"
types-python-dateutil = "^2.8.17"
types-pytz = "^2021.3.5"
types-toml = "^0.10.7"
uvloop = "^0.16.0"
wrapt = "^1.14.1"
```

I'm also currently deploying my bot using `python3.9` which is where I'm seeing these CloudFlare rate limits happen. Tho I am in the process of migrating my codebase to use `python3.10`.
